### ISSUE TITLE
pyyaml fails when installing

### ISSUE THREAD

**Issue by Peyton-Smith05** [panda-re/lava#66]
Howdy,

I am currently trying to run ``python2 setup.py`` and I am getting an issue with the package dependency pyyaml. I am running on a virtual box Ubuntu 16.04.07. Below is the error output.

```cli
Step 43/55 : RUN pip install pyyaml
 ---> Running in 6ee13682f2c0
[91mDEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
[0mCollecting pyyaml
  Downloading PyYAML-5.4.1.tar.gz (175 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'error'
[91m  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python /usr/local/lib/python2.7/dist-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpAfEf97
       cwd: /tmp/pip-install-c2R7ku/pyyaml
  Complete output (46 lines):
  running egg_info
  creating lib/PyYAML.egg-info
  writing lib/PyYAML.egg-info/PKG-INFO
  writing top-level names to lib/PyYAML.egg-info/top_level.txt
  writing dependency_links to lib/PyYAML.egg-info/dependency_links.txt
  writing manifest file 'lib/PyYAML.egg-info/SOURCES.txt'
  Traceback (most recent call last):
    File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
      main()
    File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/pep517/_in_process.py", line 114, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/tmp/pip-build-env-K1T3cu/overlay/lib/python2.7/site-packages/setuptools/build_meta.py", line 146, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=['wheel'])
    File "/tmp/pip-build-env-K1T3cu/overlay/lib/python2.7/site-packages/setuptools/build_meta.py", line 127, in _get_build_requires
      self.run_setup()
    File "/tmp/pip-build-env-K1T3cu/overlay/lib/python2.7/site-packages/setuptools/build_meta.py", line 142, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 295, in <module>
      python_requires='>=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*, !=3.4.*, !=3.5.*',
    File "/tmp/pip-build-env-K1T3cu/overlay/lib/python2.7/site-packages/setuptools/__init__.py", line 162, in setup
      return distutils.core.setup(**attrs)
    File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
      dist.run_commands()
    File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
      self.run_command(cmd)
    File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/tmp/pip-build-env-K1T3cu/overlay/lib/python2.7/site-packages/setuptools/command/egg_info.py", line 296, in run
      self.find_sources()
    File "/tmp/pip-build-env-K1T3cu/overlay/lib/python2.7/site-packages/setuptools/command/egg_info.py", line 303, in find_sources
      mm.run()
    File "/tmp/pip-build-env-K1T3cu/overlay/lib/python2.7/site-packages/setuptools/command/egg_info.py", line 534, in run
      self.add_defaults()
    File "/tmp/pip-build-env-K1T3cu/overlay/lib/python2.7/site-packages/setuptools/command/egg_info.py", line 570, in add_defaults
      sdist.add_defaults(self)
    File "/tmp/pip-build-env-K1T3cu/overlay/lib/python2.7/site-packages/setuptools/command/py36compat.py", line 36, in add_defaults
      self._add_defaults_ext()
    File "/tmp/pip-build-env-K1T3cu/overlay/lib/python2.7/site-packages/setuptools/command/py36compat.py", line 120, in _add_defaults_ext
      self.filelist.extend(build_ext.get_source_files())
    File "setup.py", line 201, in get_source_files
      self.cython_sources(ext.sources, ext)
    File "/usr/lib/python2.7/distutils/cmd.py", line 105, in __getattr__
      raise AttributeError, attr
  AttributeError: cython_sources
  ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python /usr/local/lib/python2.7/dist-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpAfEf97 Check the logs for full command output.
[0m
[32m[setup.py] [39m[1mIn LAVA dir at /home/vboxuser/Desktop/lava[0m

[32m[setup.py] [39m[1mInstalling LAVA apt-get dependencies[0m

[32m[setup.py] [39m[1mRunning [sudo apt-get -y install libjsoncpp-dev postgresql jq python-psycopg2 python-sqlalchemy socat libpq-dev cmake docker.io bc python-pexpect python-psutil python-lockfile genisoimage inotify-tools build-essential python-pip libprotobuf-c0-dev libodb-pgsql-2.4 libfdt-dev] . . . [0m

[32m[setup.py] [39m[1mChecking if user is in docker group[0m

[32m[setup.py] [39m[1mChecking that lava32 docker is properly built[0m

[32m[setup.py] [39m[1mRunning [docker build -t lava32 /home/vboxuser/Desktop/lava/docker] . . . [0m

[31m[setup.py] [39m[1m[docker build -t lava32 /home/vboxuser/Desktop/lava/docker] cmd did not execute properly.[0m
```

If anyone has come across this problem before or could help with a solution I would appreciate the help!

**Comment by AndrewQuijano** [comment]
Sorry for the delay, but I should note LAVA is being fully re-modernized, hope to get this fully updated by August latest.
